#!/bin/bash
set -e

if [ -n "$SUDO_USER" ] && [ "$SUDO_USER" != "root" ]; then
    USER_HOME=$(eval echo "~$SUDO_USER")
    if [ ! -f "$USER_HOME/.config/kicad_loader/config.json" ]; then
        mkdir -p "$USER_HOME/.config/kicad_loader"
        cp /usr/share/kicad_loader/config.json "$USER_HOME/.config/kicad_loader/"
        chown -R "$SUDO_USER":"$SUDO_USER" "$USER_HOME/.config/kicad_loader"
        echo "Konfiguracja została skopiowana do $USER_HOME/.config/kicad_loader/"
    else
        echo "Znaleziono plik 'config.json' w $USER_HOME/.config/kicad_loader/"
fi
fi

read -p "Czy chcesz zainstalować i uruchomić usługę kicad-loader w systemd? (y/N): " choice
case "$choice" in
    y|Y )
        systemctl daemon-reload
        systemctl enable kicad-loader.service
        echo "Usługa kicad-loader enabled"
        echo "Do oglądania logów: sudo journalctl -u kicad-loader.service -f"
        ;;
    * )
        echo "Pominięto instalację usługi systemd."
        ;;
esac

exit 0
